// Generated by CoffeeScript 1.4.0
var pop, push;

push = function(element) {
  return function(stack) {
    var newStack, value;
    value = element;
    newStack = [element].concat(stack);
    return {
      value: value,
      stack: newStack
    };
  };
};

pop = function() {
  return function(stack) {
    var newStack, value;
    value = stack[0];
    newStack = stack.slice(1);
    return {
      value: value,
      stack: newStack
    };
  };
};
