// Generated by CoffeeScript 1.4.0
var filter, _;

_ = require('underscore');

module.exports = filter = (function() {

  function filter() {}

  filter.numbers = _.range(10);

  filter.odds = _(numbers).filter(function(x) {
    return x % 2 === 1;
  });

  filter.evens = _(numbers).filter(function(x) {
    return x % 2 === 0;
  });

  return filter;

})();
